// Auto-generated by stellar-contracts-kit
// Contract : CAFSRWCW6DUFA4VSMBR6LH3LDJH5ZSPGFBJEV4B52GIS353AIJ2POEAO
// Network  : testnet
// Re-run `npx sck generate` to update after a contract upgrade.

// Custom Types

/** @typedef {{ content: string, id: bigint, title: string }} Note */

// Contract Interface

/**
 * @typedef {Object} notescean
 * @property {import('stellar-contracts-kit').ContractMethodFn<Array<Note>, []>} get_notes
 * @property {import('stellar-contracts-kit').ContractMethodFn<string, [title: string, content: string]>} create_note
 * @property {import('stellar-contracts-kit').ContractMethodFn<string, [id: bigint]>} delete_note
 */

export const CONTRACT_ID = 'CAFSRWCW6DUFA4VSMBR6LH3LDJH5ZSPGFBJEV4B52GIS353AIJ2POEAO'
